### ISSUE TITLE
Text becomes bigger from second line onwards in subtitle 2 on Native Mode

### ISSUE THREAD

**Issue by idanrm** [muzuiget/dualsub-support#583]
Hello,

I have noticed that whenever there is more than one line in the subtitle 2 part of Native Mode, the text becomes bigger (probably resorting to the default CC settings of YouTube).

It looks like this:
![image](https://github.com/muzuiget/dualsub-support/assets/144908547/a8cb69a2-67cd-4f83-b7e7-87d5af35dbd0)

(the font size of the line containing the text "thinking about" is bigger)

You can see it in this video in 18:15:
https://www.youtube.com/watch?v=ZNwGH28_PeU&ab_channel=HowtolearnArabicwithSahar

Could you please look into it?

Thanks

**Comment by muzuiget** [comment]
This is expected. The HTML of YouTube's native subtitles uses inline styles(the `style` attribute), so custom CSS cannot override it:

```css
 /* don't work, the `style` attribute in HTML has higher priority. */
.caption-visual-line:nth-child(2) > span {
    font-size: 80%;
}
```

But there is a hack: use the `::first-line` pseudo-element:

```css
.caption-visual-line:nth-child(2) > span::first-line {
    font-size: 80%;
}
```

That is why the font size of 2nd line is reverted back to `100%`.
